# Generated by Django 4.1.2 on 2022-11-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publisherID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('publisherName', models.CharField(max_length=128, unique=True)),
                ('publisherDescription', models.TextField()),
                ('addedTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('publisherImage', models.ImageField(upload_to='images/publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('gameID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('cheatData', models.TextField(default='')),
                ('addedTime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverImage', models.ImageField(upload_to='images/gamecovers')),
                ('coverBanner', models.ImageField(upload_to='images/gamebanners')),
                ('gamePublisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browserapp.publishers')),
            ],
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['title'], name='browserapp__title_129074_idx'),
        ),
    ]
